CREATE DATABASE 'D:\ezsem\DB\LOGISTICS.fdb' user 'SYSDBA' password 'masterkey';
commit;
CONNECT 'D:\ezsem\DB\LOGISTICS.fdb' user 'SYSDBA' password 'masterkey';

CREATE TABLE SHEDULE ( 
	ID                   integer  NOT NULL,
	ID_TRANSPORTATION    integer  NOT NULL,
	ARR_DATE             timestamp(10)  NOT NULL,
	CONSTRAINT PK_SHEDULE UNIQUE ( ID_TRANSPORT ) ,
	CONSTRAINT PK_SHEDULE_1 UNIQUE ( ID_PROVIDER ) ,
	CONSTRAINT PK_SHEDULE_2 UNIQUE ( ID_CLIENT ) ,
	CONSTRAINT PK_SHEDULE_3 PRIMARY KEY ( ID )
 );

CREATE TABLE TRANSPORTATION ( 
	ID                   integer  NOT NULL,
	ID_TRANSPORT         integer  NOT NULL,
	ID_ORD               integer  NOT NULL,
	CONSTRAINT PK_TRANSPORTATION PRIMARY KEY ( ID ),
	CONSTRAINT PK_TRANSPORTATION_0 UNIQUE ( ID_ORD ) ,
	CONSTRAINT PK_TRANSPORTATION_1 UNIQUE ( ID_TRANSPORT ) 
 );

CREATE TABLE ORD ( 
	ID                   integer  NOT NULL,
	ID_PROVIDER          integer  NOT NULL,
	ID_CLIENT            integer  NOT NULL,
	ID_LOAD              integer  NOT NULL,
	QUANTITY             integer  NOT NULL,
	AMOUNT_COST          float  NOT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY ( ID ),
	CONSTRAINT PK_ORD UNIQUE ( ID_PROVIDER ) ,
	CONSTRAINT PK_ORD_0 UNIQUE ( ID_LOAD ) ,
	CONSTRAINT PK_ORD_1 UNIQUE ( ID_CLIENT ) 
 );

CREATE TABLE PROVIDER ( 
	ID                   integer  NOT NULL,
	NAME                 varchar(20)  NOT NULL,
	SURNAME              varchar(20)  NOT NULL,
	OLDNAME              varchar(20)  NOT NULL,
	FIRM                 varchar(20)  ,
	ADDRESS              varchar(100)  NOT NULL,
	PHONE_NUMBER         integer  NOT NULL,
	CONSTRAINT PK_PROVIDER PRIMARY KEY ( ID )
 );

CREATE TABLE TRANSPORT ( 
	ID                   integer  NOT NULL,
	NAME                 varchar(20)  NOT NULL,
	CAPACITY             float  NOT NULL,
	CONSTRAINT PK_TRANSPORT PRIMARY KEY ( ID )
 );

CREATE TABLE CLIENT ( 
	ID                   integer  NOT NULL,
	NAME                 varchar(20)  NOT NULL,
	SURNAME              varchar(20)  NOT NULL,
	OLDNAME              varchar(20)  NOT NULL,
	ADDRESS              varchar(100)  NOT NULL,
	PHONE_NUMBER         integer  NOT NULL,
	CONSTRAINT PK_CLIENT PRIMARY KEY ( ID )
 );

CREATE TABLE LOAD ( 
	ID                   integer  NOT NULL,
	NAME                 varchar(20)  NOT NULL,
	WEIGHT               float  NOT NULL,
	VOLUME               float  NOT NULL,
	COST                 float  NOT NULL,
	CONSTRAINT PK_LOAD PRIMARY KEY ( ID )
 );

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT FOREIGN KEY ( ID ) REFERENCES ORD( ID_CLIENT ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE LOAD ADD CONSTRAINT FK_LOAD FOREIGN KEY ( ID ) REFERENCES ORD( ID_LOAD ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ORD ADD CONSTRAINT FK_ORD_0 FOREIGN KEY ( ID ) REFERENCES TRANSPORTATION( ID_ORD ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PROVIDER ADD CONSTRAINT FK_PROVIDER FOREIGN KEY ( ID ) REFERENCES ORD( ID_PROVIDER ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSPORT ADD CONSTRAINT FK_TRANSPORT_0 FOREIGN KEY ( ID ) REFERENCES TRANSPORTATION( ID_TRANSPORT ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSPORTATION ADD CONSTRAINT FK_TRANSPORTATION FOREIGN KEY ( ID ) REFERENCES SHEDULE( ID_TRANSPORTATION ) ON DELETE CASCADE ON UPDATE CASCADE;
commit;