CONNECT 'D:\ezsem\DB\LOGISTICS3.fdb' user 'SYSDBA' password 'masterkey';

CREATE TABLE TYPE (
    ID    INTEGER NOT NULL,
    NAME  VARCHAR(20) NOT NULL,
    COST  FLOAT NOT NULL
);

CREATE TABLE INSURANCE (
    ID           INTEGER NOT NULL,
    ID_LOAD      INTEGER NOT NULL,
    RETURN_COST  FLOAT NOT NULL
);

ALTER TABLE TYPE ADD PRIMARY KEY (ID);
ALTER TABLE INSURANCE ADD CONSTRAINT PK_INSURANCE PRIMARY KEY (ID);

ALTER TABLE ORD ADD ID_INSURANCE INTEGER NOT NULL;
ALTER TABLE LOAD ADD ID_TYPE INTEGER NOT NULL;

ALTER TABLE LOAD ADD CONSTRAINT FK_LOAD_1 FOREIGN KEY (ID_TYPE) REFERENCES TYPE (ID);
ALTER TABLE INSURANCE ADD CONSTRAINT FK_INSURANCE_1 FOREIGN KEY (ID_LOAD) REFERENCES LOAD (ID);
ALTER TABLE ORD ADD CONSTRAINT FK_ORD_4 FOREIGN KEY (ID_INSURANCE) REFERENCES INSURANCE (ID);

commit;
